### ISSUE TITLE
Toggle function

### ISSUE THREAD

**Issue by timsofteng** [jose-elias-alvarez/buftabline.nvim#1]
Hello. Can it be displayed buy some toggle function? E.g. I toggle action it and bufline appears. Then I toggle same actions second time and it disappears.

**Comment by jose-elias-alvarez** [comment]
The easiest way to control whether the tabline is shown is by using Vim's `showtabline` setting. Here is a simple Lua function that'll toggle the setting and assign it to a Vim command, `ToggleTabline`, that you can call from the command line or bind to a key:

```lua
_G.toggle_tabline = function()
    local showtabline = vim.api.nvim_get_option("showtabline")
    if showtabline > 0 then
        vim.api.nvim_set_option("showtabline", 0)
    else
        vim.api.nvim_set_option("showtabline", 2)
    end
end

vim.cmd("command! ToggleTabline lua toggle_tabline()")
```

At the moment, the tabline will always start shown when the plugin is loaded, but I can enable an option to start hidden if that's something people are interested in.

**Comment by timsofteng** [comment]
@jose-elias-alvarez yep, it would be nice to have disable on startup option. And wrap toggle function to as well it's good to keep config file cleaner.

**Comment by jose-elias-alvarez** [comment]
All set!
