### ISSUE TITLE
Code base rewrite

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/buftabline.nvim#11]
Fundamentally, what the plugin does is very simple: get a list of loaded buffers, then generate a formatted string based on those buffers and their statuses. My goal is to restructure the code to reflect that structure more clearly and make future maintenance / modification easier.

As part of the rewrite, I plan on making some breaking changes to configuration options, which I think have gotten a bit out of hand. I want to remove most of the command options, including `kill_maps` and `custom_command`, but leave the underlying `buftarget` method exposed so users can create the commands they're actually interested in. I also want to remove some of the options that I consider useless, like `disable_commands` and `show_no_name_buffers`. 

For formatting, I want to consolidate the available options into something like the [tmux status line](https://tao-of-tmux.readthedocs.io/en/latest/manuscript/09-status-bar.html), which should both streamline setup and allow for more customization. As part of that, I plan on adding in the following features:

- [x] #9
- [x] #10
- [x] #12 
- [x] #13
- [x] #14
- [x] Customize modified / read-only markers

If anyone happens to see this and has additional requests / feedback, feel free to post it. I hope to have time to work on this later this month.

**Comment by jasper-schnabel** [comment]
It would be very cool to have an option to set an offset, to prevent buftabline from drawing above vertical sidebar splits, for example a filetree, to ensure tabs begin with the shown buffer.

Maybe something like this, but it can also be done differently:
```lua
offsets = { { filetype = 'NvimTree', offset = 40 }, { filetype = 'Example', offset = 20 } }
```
Feel free to not include this if it doesn't stick to the philosophy of this plugin.

**Comment by jose-elias-alvarez** [comment]
So if I understand correctly, the offset option would pad the whole tab bar with spaces when a certain filetype is open? My initial reaction is that it's a bit out of scope, but I can consider it as part of the rewrite. Do any of the other tabline plugins have a similar feature I can use as a reference?

**Comment by jasper-schnabel** [comment]
Take a look at:

https://github.com/akinsho/nvim-bufferline.lua#sidebar-offset
https://github.com/romgrk/barbar.nvim#integration-with-filetree-plugins

But if this idea is out of scope feel free to not integrate this feature in your rewrite.
