### ISSUE TITLE
Option to disable the [+] (modified buffer symbol) in the tab's name

### ISSUE THREAD

**Issue by mroavi** [jose-elias-alvarez/buftabline.nvim#14]
I couldn't find an option to disable this. My preference would be to use rather the modified highlight groups (later when they become available) rather than appending [+] to the name since it displaces all tabs to the right.

**Comment by jasper-schnabel** [comment]
Maybe it would be nice to have an option to set the:
```lua
modified_buffer_symbol = '⏺'
```
for showing modified buffers.

**Comment by jose-elias-alvarez** [comment]
Great idea!

**Comment by jose-elias-alvarez** [comment]
Closed by #16.
