### ISSUE TITLE
Breaking changes in latest version

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/buftabline.nvim#17]
In #16, I rewrote the entire code base to both streamline configuration and enable more flexibility. As a result, I made the following breaking changes to the plugin:

- Removed visual customization options `index_format`, `padding`, and `icons`, all of which are now available under the new `tab_format` option (see the README for more info)
- Removed map options `kill_maps`, `custom_command`, and `custom_command_prefix` in favor of a new helper, `buftabline.map()`, which makes it easier to write custom commands targeting buffers in the bufferline (again, please see the README)
- Completely removed options `modifier`, `show_no_name_buffers`, and `next_indicator`, which I deemed unnecessary

Other non-breaking changes:

- `icon_colors` is set to `true` by default, which is in line with other plugins that integrate with nvim-web-devicons (e.g. telescope.nvim)
- `hlgroups` is now a table and allows for further customization of buffer colors, but (for now) the old config options `hlgroup_current` and `hlgroup_normal` are still valid

Thank you for your patience! If I removed an option you relied on, broke something, or otherwise did something you are unhappy about, please let me know in this issue or open up another. 

Edit: tabpage handling has been removed completely (see below for more info).

**Comment by p00f** [comment]
I don't know if this is related, but the wrong characters seem to be highlighted with the devicon colours:
![image](https://user-images.githubusercontent.com/36493671/127596423-6e093f12-694e-48f6-b400-4412a504b1c8.png)
![image](https://user-images.githubusercontent.com/36493671/127596525-52c1e017-b5e0-4973-8243-98023c7497d3.png)
![image](https://user-images.githubusercontent.com/36493671/127596680-978ef26e-54c2-4c13-acf7-e2b8b6714525.png)

My config:
```lua
require('buftabline').setup {
    tab_format = ' #{n}: #{b}#{f} #{i} ',
}
```

**Comment by jose-elias-alvarez** [comment]
Definitely related, and I see the same problem on my end with that same format. Will look into it – thanks for reporting.

**Comment by jose-elias-alvarez** [comment]
@p00f Multibyte characters are a pain, but I think 7d82600f8a49e657120f714011bfd51783707d7d should take care of it, so let me know!

**Comment by p00f** [comment]
Yes :partying_face:

**Comment by jdrouhard** [comment]
`show_no_name_buffers` is still useful for when you first open nvim. Instead of seeing a completely empty, single-colored bar at the top, you at least get one buffer called `[No Name]`. Maybe I'm weird, but I sorta like having that when I first open nvim as opposed to a blank line at the top. It disappears as soon as a file is actually opened.

**Comment by jose-elias-alvarez** [comment]
Update: in the interest of keeping the plugin as simple as possible, I've removed tabpage handling (it's not really compatible with the idea of a buffer tabline, anyways) and reinstated most of the changes from #23. Sorry again for any trouble – this is likely to be the last significant update to the plugin.
