### ISSUE TITLE
BufTabLineFill highlight support

### ISSUE THREAD

**Issue by mroavi** [jose-elias-alvarez/buftabline.nvim#19]
Would it be possible to support highlighting the empty BufTabLine area using `BufTabLineFill`? By default, it should inherit the color of `TabLineFill`, but it would be nice if this can be overwritten using this plugin.

**Comment by jose-elias-alvarez** [comment]
Sure, I've recently added a simple padding mechanism to support right-aligned tabpage tabs, so it should be easy to wire it up to get highlighted and always fill available empty space. Will work on this soon.

**Comment by jose-elias-alvarez** [comment]
Let me know if 867c50908e37803efd5ad019a6f4b55e67cfe2fb does what you want.

**Comment by mroavi** [comment]
That's exactly what I wanted. Thanks again.
