### ISSUE TITLE
Maintain icon colors when changing &background

### ISSUE THREAD

**Issue by polyzen** [jose-elias-alvarez/buftabline.nvim#20]
A couple of plugins that manage this are [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) and (yet to be merged) [lualine.nvim](https://github.com/hoob3rt/lualine.nvim/issues/280#issuecomment-892733791).

**Comment by jose-elias-alvarez** [comment]
Thanks for the links! From the lualine changes, I can see that this would be pretty easy to implement. I have some other changes to merge so I'll add this in and push it soon.

**Comment by jose-elias-alvarez** [comment]
Could you update and let me know if it works as expected now? It should reset and recreate the icon colors when the background or colorscheme changes.

**Comment by polyzen** [comment]
Works as expected, thank you very much!
