### ISSUE TITLE
`go_to_buffer` function no longer exists

### ISSUE THREAD

**Issue by deathlyfrantic** [jose-elias-alvarez/buftabline.nvim#24]
As far as I can tell the only place this string exists is in the readme.

**Comment by jose-elias-alvarez** [comment]
Thanks for catching this! I missed this in a recent rewrite and will correct it when I have a chance.

**Comment by jose-elias-alvarez** [comment]
Closed by 7a822f1ff6399ea873544f1b81412530f7bb69dc.
