### ISSUE TITLE
Support filetypes set via autocmds

### ISSUE THREAD

**Issue by dstanberry** [jose-elias-alvarez/buftabline.nvim#25]
https://github.com/jose-elias-alvarez/buftabline.nvim/blob/bf5480af6c90c226f7c575aa20a2ec604de9531f/lua/buftabline/buftab.lua#L62

could be replaced with the following:
```lua
vim.api.nvim_buf_get_option(self.buf.bufnr, "filetype"),
```

**Comment by jose-elias-alvarez** [comment]
This would be great, but nvim-web-devicons currently indexes icons by extension, not filetype (see [this issue](https://github.com/kyazdani42/nvim-web-devicons/issues/29)). If that's solved upstream, we could definitely support it here.

**Comment by dstanberry** [comment]
Ah right, I remember watching this issue a while back and forgot about it. As a fallback of sorts, would you be open to having the suggestion applied as a last-gasp attempt if `fnamemodify(...)` returns an empty string?

**Comment by jose-elias-alvarez** [comment]
Sure, seems like a sensible change. PR welcome!
