### ISSUE TITLE
No icon for python and (possibly) more languages

### ISSUE THREAD

**Issue by konradmalik** [jose-elias-alvarez/buftabline.nvim#5]
Hey, just noticed this bug and investigated what is going on.
The tabline not show icons for python buffers, while for lua for example they are perfectly fine.
Turns out that 'nvim-web-devicons' requires extension, not a filetype while getting the icon. For lua it just happens to be the same thing.
Concretely, https://github.com/jose-elias-alvarez/buftabline.nvim/blob/cbc4839330a12b3ecfd48c415f890d1f3ed3431c/lua/buftabline/buffers.lua#L95 should have the extension, not filetype as the second argument. This can be easily tested that for "py" it returns the proper icon, but for "python" it is empty.

**Comment by jose-elias-alvarez** [comment]
Nice catch! You're exactly right. I don't use devicons myself, so I tested it briefly using a Lua file, a .zsh file, and a Vimscript file... all of which worked, but only as a coincidence. 

Should be fixed in 98f0f302a71a0fca190dff999e3e15103c128b2b. Let me know.

**Comment by konradmalik** [comment]
yup, now works OK, thanks!
