### ISSUE TITLE
Opening neovim with an dashboard buffer give lua error

### ISSUE THREAD

**Issue by CronyAkatsuki** [jose-elias-alvarez/buftabline.nvim#6]
I have my neovim setup in a way that it will show [dashboard-nvim](https://github.com/glepnir/dashboard-nvim) when I'm don't specify a file, which gives me an error for this plugin.

Error is `E5108: Error executing lua .../packer/start/buftabline.nvim/lua/buftabline/buffers.lua:89: attempt to index local 'last_buffer' (a nil value)`

![pic-window-210430-0815-28](https://user-images.githubusercontent.com/64900606/116656576-32a3a380-a98d-11eb-9f7f-d5ea50c4b114.png)

> screenshot of the error

**Comment by jose-elias-alvarez** [comment]
Just pushed a fix that should prevent your specific error. Does the plugin behave normally otherwise?

**Comment by CronyAkatsuki** [comment]
Everything otherwise is completely normal.

**Comment by CronyAkatsuki** [comment]
Your latest fixed the error. No error anymore.

**Comment by jose-elias-alvarez** [comment]
Glad to hear it, thanks for confirming and for the bug report!
