### ISSUE TITLE
[feature suggestion] Colored icons

### ISSUE THREAD

**Issue by jasper-schnabel** [jose-elias-alvarez/buftabline.nvim#7]
Hi,
Thanks for the very cool plugin, I really like the simple spirit.

I don't know how difficult it is to implement colored icons, but it would be nice to see an option like this.

Feel free to close this issue if it is against the idea of this plugin.

**Comment by jose-elias-alvarez** [comment]
I know nvim-web-devicons has color support for icons, but I don't know what it would take to show them in the tabline (currently the plugin just slaps a highlight group over the whole tab and calls it a day). I'll take a look at how other tabline plugins implement colored icons when I have a chance this weekend and get back to you re: feasibility.

**Comment by jose-elias-alvarez** [comment]
This was a little trickier than expected, but with some tweaking, barbar.nvim's implementation (which creates a new highlight group using the icon color as the foreground and the original background color) did the trick. I just pushed a new commit with the feature, so let me know if it does what you wanted.

**Comment by jasper-schnabel** [comment]
The colored icons work perfectly, one last thing, would it be possible that only the active buffers/tabs have colored icons and the inactive ones do not, otherwise it works exactly as desired, Thanks!

**Comment by jose-elias-alvarez** [comment]
Nice idea – I just added a couple of additional options for `icon_colors`. Setting it to `current` should get you what you want.

**Comment by jasper-schnabel** [comment]
Works very well, thanks for the quick implementation :+1:
